tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap homebrew/cask-fonts

brew "mas"
brew "git"
brew "fish"
brew "fzf"
brew "nodebrew"
brew "rbenv"
brew "go"
brew "ssh-copy-id"
brew "fish"
brew "ghq"
brew "yarn"
brew "tmux"
brew "jq"

cask "google-chrome"
cask "google-japanese-ime"
cask "dash"
cask "visual-studio-code"
cask "docker"
cask "postman"
cask "alfred"
cask "spotify"
cask "slack"
cask "karabiner-elements"
cask "font-cica"

mas "The Unarchiver", id: 425424353
